### ISSUE TITLE
Input Value range

### ISSUE THREAD

**Issue by MoSuunny** [nicoboou/chadavit#2]
Hello!
I  have a question about the pixel value range in images.

Do you normalize the pixel values between zero and one before feeding them into the network, or do you keep them in the original range of zero to 256? If you do normalize, which normalization technique do you use, and what is the resulting range of the final image?

**Comment by nicoboou** [comment]
Hi, images were normalized channel-wise within the range (0,255) using following normalization formula:

`uint8_channel = 255 * clip_{0, 1}((channel - min_percentile) / (max_percentile - min_percentile))`

where `min_percentile` is the 1st percentile value of the channel, `max_percentile` is the 99.99th percentile value of the channel, and `clip_{0, 1}(x)` is a function that clips the values of `x` between 0 and 1.

@MoSuunny does it help ?
